name: instacare
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

 # sdk: '>=2.18.0-165.1.beta <3.0.0'



dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_switch: ^0.3.2
  get: ^4.6.5
  gap:
  connectivity_plus: ^4.0.1
  get_storage: ^2.1.1
  flutter_screenutil: ^5.8.2
  image_picker: ^0.8.7+5
  flutter_svg: ^2.0.6
  intl: ^0.18.1
  calendar_date_picker2: ^0.5.2
  flutter_cool_card_swiper: ^0.0.4
  group_radio_button: ^1.3.0
  file_picker: ^4.0.0
  dropdown_plus: ^0.0.9
  dropdown_button2: ^2.1.3
  flutter_advanced_calendar: ^1.4.1
  flutter_event_calendar: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
   - assets/profileFlow/
   - assets/authFlow/
   - assets/drowerFlow/
   - assets/dashBoardFlow/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
